### ISSUE TITLE
design is terrible

### ISSUE THREAD

**Issue by wiiam** [installgen2/tox.chat#2]
try again

**Comment by installgen2** [comment]
:(

**Comment by SkyzohKeyx** [comment]
I can help with css if you want :)

**Comment by ahstro** [comment]
What's terrible about it?

**Comment by SkyzohKeyx** [comment]
All. The design is badly designed. :x 
If i don't make my .vapi file working, then i'll make a little/clean/simple website for Tox :)

**Comment by wiiam** [comment]
@installgen2 add a fixed navbar

**Comment by ahstro** [comment]
@wiiam The current navbar doesn't navigate to things on the page, so fixing it doesn't really make sense. Should it be replaced with on-page navigation?

**Comment by wiiam** [comment]
@ahstro but what if I'm at the bottom of the page and want to go to the wiki? Do you expect me to scroll all the way to the top?

**Comment by wiiam** [comment]
@ahstro btw nice job on the antox website

**Comment by wiiam** [comment]
@ahstro the navbar at the top should probably be fixed though

**Comment by installgen2** [comment]
@wiiam no fixed navbar, just no.

**Comment by stal888** [comment]
cram it @wiiam

**Comment by installgen2** [comment]
Closing this, it's just shitposting anyway.
