### ISSUE TITLE
Ugly favicon

### ISSUE THREAD

**Issue by installgen2** [installgen2/tox.chat#27]
Easily visible white patches make it look like total shit smh fam tbh

**Comment by installgen2** [comment]
@ProMcTagonist

**Comment by installgen2** [comment]
@ProMcTagonist #30 didn't really fix it

![a](https://sr.ht/5F7M.png)

**Comment by ProMcTagonist** [comment]
What should it look like?

**Comment by installgen2** [comment]
The white should be replaced with alpha transparency

**Comment by installgen2** [comment]
![a](https://sr.ht/ysxK.png)
