### ISSUE TITLE
Edit: New website discussion/planning

### ISSUE THREAD

**Issue by dcharles525** [installgen2/tox.chat#4]
I can help a little. After reading through your blog post, I am not sure what is needed first. Anything specific you'd like done @installgen2

**Comment by installgen2** [comment]
@dcharles525 A lot of people have complained about the download and social buttons, and I'm not happy with them myself either. If you could help redesign those, that'd be great.

**Comment by dcharles525** [comment]
@installgen2 Sure, i think they look better if they matched the UI design of the actual clients.

**Comment by dcharles525** [comment]
@installgen2 Also, is using bootstrap a must for everything? Or can I just write css from scratch?

**Comment by installgen2** [comment]
I'm not a web developer, I have no idea or preference...

**Comment by dcharles525** [comment]
@installgen2 well then, scratch just doing the buttons and icons, I will redo everything to match the current qTox and uTox UI's.

**Comment by stal888** [comment]
@dcharles525 that font and colour choice is quite bland, and the formatting isn't great either. 

what is wrong with the current design?

**Comment by Zer0-One** [comment]
@dcharles525 there's nothing wrong with @installgen2 's current design; imo, you should focus your efforts on improving it.

**Comment by dcharles525** [comment]
@stal888 haven't really gotten a chance to do some designing, give me some time before taking a deep look, I really feel like I can make something unique here. 

@Zer0-One According to his blog post people don't like it, layout is pretty good, but from a marketing and  overall design standpoint the colors and elements do match the software, which is a shame, give me some time and I can show you what I am thinking.

*Not trying to hate on installgen2 design or anything, just wanting to really bring the site to life.

**Comment by installgen2** [comment]
@dcharles525 I'm not sure "matching the site design to the software" is a good idea for a project like Tox, to begin with, the "design" you associate with Tox, is really just what's being implemented in two major clients. In the very foreseeable future, qTox or uTox could make their own original (and maybe better) design, or another client not following the same mockup could join the ranks of the most popular, and possibly depreciate qTox and uTox.

Also, I personally quite dislike the UI mockup that uTox and qTox follow, for reasons I don't want to get into right now, but what's more important is it certainly doesn't fit a website. The UI mockup is a design which is debatably fitting for a client, but on a website, it simply is not what gives the right image for Tox.

If you would really rather write your own based from the Tox mockup/qTox + uTox's UI, then I'm interested to see the results, but I think improving the current design would be more worthwhile.

also wut?
>According to his blog post people don't like it

**Comment by dcharles525** [comment]
So this was more what I was thinking to early lookers in my repo. 

Let me explain. 

Ok throw all the UI mumbo jumbo out of the way, I was thinking something like this.....dark and encompassing, the current tox.chat is actually pretty good, somethings, need a little change. The flat/bootstrap design stuff has been overused all over the internet, not that bootstrap is good looking, but it doesn't really stand out anymore. and I just wanted to put Tox out ahead of other chat clients. Here is a rough html/css mockup of what I was thinking. 

I see what you are saying about other clients doing their own thing, which concerns me for the daily users, but I think this can be well adapted to fit Tox as a whole. 

Keep throwing stuff out there, I am really here to build what the main Tox team thinks is best.

![screenshot from 2015-09-24 21 04 03](https://cloud.githubusercontent.com/assets/4961680/10090647/e7898006-62ff-11e5-9fa1-992756ad21b2.png)

**Comment by dcharles525** [comment]
Also in the mean time I will stop writing any code until a decision is reached. Really just wanna help Tox out :)

**Comment by installgen2** [comment]
I'm going to be honest, that does look pretty cool, but there are some problems I still have with going that direction regarding design. Also, I'd rather discuss this in IRC on #tox-dev, there are a lot more people there that can give their opinions.

**Comment by dcharles525** [comment]
@installgen2 Awesome, I would like to hear these concerns, I will hop on IRC then :)

**Comment by ProMcTagonist** [comment]
https://github.com/Tox/Tox-Website/issues/8

**Comment by installgen2** [comment]
As I said in IRC...

02:41 \<installgen2\> well this debate has gone far from website design
02:41 \<installgen2\> this is about tox's overall design

**Comment by SkyzohKeyx** [comment]
@dcharles525 your HTML code is really ugly. Using <br> is a bad habitude. Also, you should uses a responsive grid system (or uses mediaqueries). Currently the website doesn't supports mobile devices which is a bad point. [See the site in live](https://rawgit.com/dcharles525/Tox.Chat/master/index.html)

**Comment by dcharles525** [comment]
The site was a quick mockup just to show my ideas to installgen2. I would
create a responsive site or dedicated mobile site if  needed. As discussed
we are working on the site that he put together and just fixing elements.

**Comment by installgen2** [comment]
During the last Tox meeting, I asked quite a few people their opinions on the site, and the overall agreement is that this site should be use, but a lot of elements should be copied from the current one. With no major design changes, unless people change their mind. I'm going to open a few issues on this repo with some things people have pointed out.

**Comment by installgen2** [comment]
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/installgen2/tox.chat?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
