### ISSUE TITLE
Ugly on large screen sizes

### ISSUE THREAD

**Issue by installgen2** [installgen2/tox.chat#5]
Lots of people have pointed out that the site looks hideous on large screens, I can't see for myself because I only have small screens. Most people have said that they prefer current tox.chat over this in regards to large screen size handling even though both websites have the same width limit iirc. Somebody in the Tox meeting said might be due to having more sections with lots of color contrast.

**Comment by installgen2** [comment]
Well, no more people have complained, if anybody has any issues or suggestions, see gitter.

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/installgen2/tox.chat?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by ovalseven8** [comment]
It's still an issue. Please reopen.

**Comment by installgen2** [comment]
It's a discussion issue, use Gitter until somebody can point out specifics.
